title: "무분별 할인 정보 모음"
description: "쉿! 이 가격은 비밀이예요"
url: "https://tosamjin.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge
lang: "ko"

# post, collection 리스트에서 썸네일 사용
teaser: true

collections:
  products:
    output: true
    permalink: /products/:title/

defaults:
  - scope:
      path: ""
      type: products
    values:
      layout: single
      show_date: false
      show_read_time: false
      author_profile: false
      related: true
      teaser: "{{ page.thumbnail }}"
